### ISSUE TITLE
1.0.0 Master Checklist

### ISSUE THREAD

**Issue by brandonLi8** [brandonLi8/portfolio-website#17]
# Checklist to be completed for 1.0.0:

## Design
- [ ] Design Document Created (Date: //)
  - [ ] Mock ups complete (Date: //)
  - [ ] Planned Browser Support
  - [ ] Favicon (Date: //)
  - [ ] Logo design (Date: //)
  - [ ] OG Preview Images (Date: //)
- [ ] Additional Screen Shots (Date: //)

## Implementation
- [x] Repository created
- [ ] License added
- [ ] [Grunt Config](https://github.com/brandonLi8/grunt-config) Added
- [ ] Code Reviewer Identified and Completed
- [ ] Verify Credits
- [ ] 404 page added
- [ ] domain/cname confirmed
- [ ] Published! (Date: //)

## Grunt Config
- [ ] `npm` initiated with `package.json`
- [ ] GitHub labels added
- [ ] `README.md` generated and updated (Date: //)
- [ ] `.gitignore` generated (Date: //)
- [ ] `travis.yml` generated and updated (Date: //)
- [ ] `.wercker.yml` generated and updated (Date: //)

## Testing
- [ ] Performance acceptable on each browser (Date: //)
- [ ] memory leak tested (Date: //)
- [ ] Feature Complete (Date: //)
- [ ] iFrame support tested
- [ ] Embedded link support
